"""Initial migration

Revision ID: 688f42ace6d9
Revises: 
Create Date: 2026-09-12 02:23:03.715655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688f42ace6d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('current_occupation', sa.String(), nullable=True),
    sa.Column('employment_preference', sa.String(), nullable=True),
    sa.Column('mobility_km', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiaries_id'), 'beneficiaries', ['id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_name'), 'beneficiaries', ['name'], unique=False)
    op.create_table('beneficiary_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiary_skills_id'), 'beneficiary_skills', ['id'], unique=False)
    op.create_index(op.f('ix_beneficiary_skills_skill_name'), 'beneficiary_skills', ['skill_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beneficiary_skills_skill_name'), table_name='beneficiary_skills')
    op.drop_index(op.f('ix_beneficiary_skills_id'), table_name='beneficiary_skills')
    op.drop_table('beneficiary_skills')
    op.drop_index(op.f('ix_beneficiaries_name'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_id'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
